name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v4
    # Login to Docker Hub. Adjust for other registries like GitHub Container Registry (ghcr.io), AWS ECR, etc.
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker build -t seyiogunniran/ecommerce-app:$(date +%s) .

    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push seyiogunniran/ecommerce-app:$(date +%s)
